export const DATA_SUCCESS = 'MOVIES_ALL_SUCCESS';
export const DATA_SECONDARY_SUCCESS = 'MOVIES_GENRE_SUCCESS';
export const DATA_ERROR = 'MOVIES_ALL_ERROR';
export const DATA_FETCHING = 'MOVIES_ALL_FETCHING';
